CREATE TABLE ADDRESS(
	
	ADDRESS_ID 	NUMBER(9) NOT NULL DEFAULT NEXTVAL('SEQ_ADDRESS_ID'),
	STREET 	VARCHAR2(128) NOT NULL,
	CITY	VARCHAR2(128) 	 NOT NULL,
	STATE  VARCHAR2(128) NOT NULL,
	LANDMARK VARCHAR2(128) NOT NULL,
	PINCODE VARCHAR2(128) NOT NULL,
	ADDRESS_VERSION	NUMBER(9) NOT NULL,
	CONSTRAINT ADDRESS_ID_PK PRIMARY KEY(ADDRESS_ID)
);

CREATE SEQUENCE SEQ_ADDRESS_ID MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 100;

CREATE TABLE PATIENT(

	PATIENT_ID 		NUMBER(9) NOT NULL DEFAULT NEXTVAL('SEQ_PATIENT_ID'),
	NAME			VARCHAR2(128) 				NOT NULL,
	ADDRESS_ID		VARCHAR2(128)				NOT NULL,
	PHONE_NUMBER  	NUMBER(12)				  	NOT NULL,
	DOB 			VARCHAR2(128)				NOT NULL,
	NATIONAL_ID 	VARCHAR2(128)				NOT NULL,
	PATIENT_VERSION	NUMBER(9)				  	NOT NULL,
	CONSTRAINT PATIENT_PK PRIMARY KEY(PATIENT_ID),
	CONSTRAINT ADDRESS_PK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE SEQUENCE SEQ_PATIENT_ID MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 100;

CREATE TABLE PATIENT_MEDICAL_HISTORY(
	
	PATIENT_MEDICAL_HISTORY_ID 	NUMBER(9) NOT NULL DEFAULT NEXTVAL('SEQ_MEDICAL_HISTORY'),
	ILLNESS 		VARCHAR2(128),
	DESCRIPTION 			VARCHAR2(128),
	HOSPITAL_ADMISSION			VARCHAR2(128),
	CONDITION VARCHAR2(128),
	CREATION_DATE	DATE,
	DISCHARGE_DATE 	DATE,
	IS_ALIVE	VARCHAR2(128),
	IS_DISCHARGED VARCHAR2(128),
	CHARGES NUMBER(10),
	PATIENT_ID NUMBER(9),
	PATIENT_MEDICAL_HISTORY_VERSION NUMBER(9),
	CONSTRAINT PATIENT_MEDICAL_HISTORY_PK  PRIMARY KEY(PATIENT_MEDICAL_HISTORY_ID),
	CONSTRAINT PATIENT_FK FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);

CREATE SEQUENCE SEQ_MEDICAL_HISTORY MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 100;

--INSERT INTO USER VALUES(999,'VARUN92','adhikari.varun92@gmail.com',919717345562,'password',1);
